gridsuite/gridstudy-app

src/components/single-line-diagram.js
No
Fearture
Single line diagram style is adapted to current theme.
=> Fix single line diagram label style

src/components/network/network-map.js
NO
Feature
At max zoom, a substations use 80% of the screen showing a big colored circle
at max zoom, the substation uses a normal chunk of the screen …
=> Use a better maxzoom

src/components/single-line-diagram.js
Setting the svg height and width attribute from the svg bounding box, so this will dynamically adjust the size of the embedding window.
Defining a max width and max height for this window.
Adding scrollbars when necessary to scroll the svg inside the window.
feature
A substation is always drawn in a fixed size window and the svg is scaled to fit into this …
=> keep_the_same_zoom_level_for_substation_with_an_activable_scroll

src/components/network/network-map.js
NO
Bug Fix
Labels are not shown on a small networks at startup. They appear when you pan/zoom once
Labels are shown
NO
=> Fix missing labels on start when viewing small networks

src/components/single-line-diagram.js, src/translations/en.json, src/translations/fr.json
NO
Feature
When a network or server error on svg fetching happens, nothing happens in the browser
When a network or server error on svg fetching happens, an error is shown in the browser
**Does this PR introduce a breaking change or deprecate an …
=> study-pane: handle network errors in svg fetch

src/components/single-line-diagram.js, src/components/study-pane.js, src/utils/rest-api.js
NO
Feature
click on a line or transformer in the sld, nothing happens
click on a line or transformer, it displays the next voltage id
NO
**Other …
=> single-line-diagram, display diagram of next voltage level on click

src/components/network/network-map.js, src/components/network/network.js, src/components/network/nominal-voltage-filter.js, src/components/study-pane.js
Feature
No possibility to filter the network elements on the map (substations, labels, lines) by nominal voltage levels
A new graphical component allows the user to check/uncheck the nominal voltage levels and filter the network elements on the map
**Does this PR introduce a breaking change or …
=> Network filtering according to nominal voltages

package.json, src/components/top-bar.js
Signed-off-by: Franck LECUYER <franck.lecuyer@rte-france.com>
Feature
Nothing happens when the user clicks on the application logo
When the user click on the application logo, the main page is now displayed
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the …
=> go to the main page of study-app when clicking on the logo

app-httpd.conf
NO
Bug fix
When browsing https://demo.powsybl.org/study-app/studies//Microgrid%20Be (notice multiple slashs), we get a white page and the javascript is crashed
When browsing https://demo.powsybl.org/study-app/studies//Microgrid%20Be (notice …
=> fix base for multiple slashs in urls

package.json, src/components/network/network-explorer.js
Feature
Currently the voltage level list in the left-side has a fixed height
The voltage level list is adapting with the web browser height …
=> Modification of the substation list to adapt to the web browser height

package-lock.json, src/components/network/network-explorer.js, src/components/network/network-map.js, src/components/network/network.js, src/components/network/nominal-voltage-filter.js, src/components/study-pane.js
No
Performance improvement
Opening of single line diagram is very slow for large grids (1 second). The reason is when a single line diagram is open, network map and nominal voltage filtering components are always re-rendered even if their data have not changed.
After analysis it …
=> Improve rendering performance

src/components/network/network-explorer.js, src/components/network/network-map.js, src/components/network/network.js, src/components/network/network.test.js, src/components/study-pane.js, src/translations/en.json, src/translations/fr.json
No
Feature
When clicking on a voltage level, only the svg is update
the map is centered on the substation of the voltage level
NO
**Other …
=> center map on substation on user clicks

src/components/network/line-layer.js, src/components/network/network-map.js, src/components/network/network.js, src/components/network/substation-layer.js, src/utils/colors.js
No
refactoring
Network  map layer are not organized and all created in NetworkMap component.
DeckGL has composite layer that allows implementing custom layers based on composition of standard layers.
I created 2 business layer: 
- substation layer: that embed everything regarding substation …
=> Use DeckGL CompositeLayer in network map 

package-lock.json, package.json, src/utils/authentication/AuthService.js
NO
Bug fix
When using the common azure tenant, oidc-client-js refuses the token because the issuer is not the same
don't refuse the token
NO
=> Hack to make oidc-client-js work with azure common tenant

src/components/network/network-map.js
When clicking on a substation label, an error svg is displayed:
=> fix click on substation text displaying an error voltage level diagram

src/utils/authentication/AuthService.js
at the root of the app after login, reload -> crash
at the root of the app after login, press back, the auth page is redisplayed and redirected and crash
=> Try to fix login after back..

src/utils/authentication/AuthService.js
When reloading, the user is not found when the authority is changed. Need to change it
=> fix auth when reloading

src/components/network/network-map.js, src/components/study-pane.js
Because of reuseMaps options of mapbox, we do not have the same "visual aspect" of study opening. When we open the second study, first map appears as it was in the previous study then it is reinitialized.
Also before data loading (network + geo data) we display the map at the lower zoom level (whole world), before zoom once data have loaded.
=> Fix map tiles flicker

src/components/study-manager.js
Case format for IEEE CDF converter was 'IEEE CDF' and not 'IEEE-CDF' in powsybl <= 3.1. Starting from powsybl 3.2 it is 'IEEE-CDF'
=> Fix IEEE CDF logo for powsybl <= 3.1

src/components/parameters.js, src/components/study-pane.js, src/redux/actions.js, src/redux/local-storage.js, src/redux/reducer.js, src/translations/en.json, src/translations/fr.json, src/utils/rest-api.js
Topological coloring of single line diagram is available in single line diagram server. This PR add a parameter in the "Single line diagram" tab to activate topological coloring instead of default nominal voltage coloring.
Signed-off-by: Geoffroy Jamgotchian <geoffroy.jamgotchian@gmail.com>
=> Add topological coloring to parameters

src/components/network/network-map.js, src/components/study-pane.js
Also I think the previous version had broken the performance optimisation of not relayouting study-explorer everytime (useCallback)
=> Use an imperative handle for centering on a substation to fix recenter

src/components/study-manager.js
When renaming a study if we pressed cancel after typing a new name and then reopened the rename popup, the name printed was the one we typed before canceling. 
Now if we cancel and reopen the study name is displayed.
also changed the icon for the rename option.
=> minor fix + changed the rename icon

src/components/app.js, src/components/create-study-form.js, src/components/study-manager.js, src/utils/dialogs.js
=> Refactor the study-app manager

src/components/network/layers/scatterplot-layer-ext.js, src/components/network/network-map.js, src/components/network/network.js, src/components/network/substation-layer.js
To avoid substation concentric circles to become to large when zooming in, we limit the max size in pixels of circles.  To do that I had to hack to scatterplot layer that does not allow to have a max pixel size depending on the object (this is a uniform and not an attribute in the GLSL).
=> Add substation max radius

src/components/study-pane.js
Correction of the substations list display which displayed only 3 substations after addition of loadflow button
Signed-off-by: NOIR Nicolas ext <nicolas.noir@rte-france.com>
=> Correction of the substations list display

src/components/network/line-layer.js
Loadflow causes an error on the lines' active power label
=> fix regression when manipulating network

app-httpd.conf
This fixes urls like "http://foo.com/bar?url=http://other.com
In the query string, slashes and colon don't have to be escaped (although they can be).
=> fix base when query string contains unescaped slashes

src/components/app.js
Reloading is mandatory because we don't know the issuer until we request the token, and we need to set the /common issuer first for the oidc-client-js library to request the token.
=> hackfix the initial silent login for azure

src/components/network/overloaded-lines-view.js
#	src/components/network/network-table.js
#	src/utils/rest-api.js
=> fix regression on overloaded-lines-view.js

src/components/network/network-explorer.js
change where onClick capture click
add stopPropagation to prevent substation oppening when focusing on it
#	src/components/network/network-explorer.js
#	src/components/study-pane.js
=> expand click zone to whole list item

src/components/network/layers/arrow-layer-vertex.glsl.js
The arrow direction pointed to the point as if the forkline
had not caused a translation along the axis of the lines (all points
are translated perpendicular to the lines, but only the first and last point
are translated parallel to the lines because of the forklines).
=> fix arrow direction on first and last segment of the line

src/components/study-pane.js
regression from bad merge in 9257e44f572 reintrocing the overlay,
because it was moved in 83aa3a931a33de8
=> Remove spurious duplicate LoaderWithOverlay

src/components/network/network-table.js
This was already partially done... It should have been the same for all tabs
but only the first one was fixed.
=> correctly remove spurious scrollbar in the network elements tables in all tabs

package.json
On the browser console we get
"An error occurred while parsing the WebWorker bundle. This is most likely due to improper transpilation by Babel; please see https://docs.mapbox.com/mapbox-gl-js/api/#transpiling-v2"
Apply the CRA solution from https://github.com/mapbox/mapbox-gl-js/issues/10565
=> Try to fix the map background not displaying anymore.

package.json
this time follow this advice about "Android 4.4.3-4.4.4" from
https://github.com/mapbox/mapbox-gl-js/issues/10565#issuecomment-890164952
=> Try again to fix the map background.

src/components/dialogs/equipment-deletion-dialog.js, src/components/dialogs/generator-creation-dialog.js, src/components/dialogs/line-creation-dialog.js, src/components/dialogs/load-creation-dialog.js, src/components/dialogs/shunt-compensator-creation-dialog.js, src/components/dialogs/substation-creation-dialog.js, src/components/dialogs/two-windings-transformer-creation-dialog.js, src/components/dialogs/voltage-level-creation-dialog.js
fix(dialogs): if forms are valid, call handleCloseAndClear without waiting fetch response, errors will be shown in snackbar
=> Fix hypothesis duplication at save

src/components/single-line-diagram.js
fixes flicker during loadflow run.
=> single-line-diagram, always reset the svg before recomputing sizes.

src/components/network/equipment-table-editors.js
Warning: React does not recognize the `inputProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `inputprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
=>  Fix warning for NumericalField input type number props

src/components/diagrams/networkAreaDiagram/network-area-diagram.js
Display an empty panel when loading a new NAD (width and height are taken from the previous one). 
When the first NAD is loading, when opening a new study, we only display the header and the loader.
=> display empty panel when loading NAD

src/components/dialogs/load-modification-dialog.js
=> Fix(LoadModificationDialog): avoid returning an object as FormHelperText children

src/components/diagrams/singleLineDiagram/single-line-diagram-pane.js, src/components/study-container.js, src/redux/reducer.js
Refactor synchCurrentTreeNode to overwrite currentTreeNode only when concenened in NETWORK_MODIFICATION_TREE_NODES_REMOVED and NETWORK_MODIFICATION_TREE_NODES_UPDATED
=> Fix Add condition to updateSld at node build

src/components/network/equipment-table.js
Warning: Failed prop type: Invalid prop `styleBottomLeftGrid` of type `string` supplied to `MultiGrid`, expected `object`.
=> Fix MultiGrid warning

src/components/diagrams/singleLineDiagram/single-line-diagram-pane.js
When a SLD is open and the currentNode is not built, there was a bug that prevented the "close" icon of the SLD to close the SLD window.
=> Fixes the bug preventing a SLD of an unbuilt node to be closed.

src/components/diagrams/singleLineDiagram/single-line-diagram-pane.js, src/components/diagrams/singleLineDiagram/single-line-diagram.js
=> Fix(SLD): avoid fetching SVG when "disabled" props when changing current node .

src/components/network-map-tab.js
=> Overloaded lines pane is now hidden when loadflow is not is 'success' state

src/components/diagrams/singleLineDiagram/single-line-diagram.js
a change in svgFinalWidth or svgFinalHeight only should not trigger
a recomputation of preferred sizes
=> Avoid loops in sld preferred sizes

package-lock.json, package.json
It updates autosuggest-highlight dependency as expected but why it's not a peer dependency in commons-ui ?
=> Use commons-ui v0.24.0

src/components/app-top-bar.js, src/components/dialogs/equipment-search-dialog.js
if searchTerm with 3 char then close and reopen the searchBar then with the same searchTerms it doesn't proc fetch
=> fix: Search equipment Infos with 3 chars doesn't work sometimes 

src/components/dialogs/generator-creation-dialog.js, src/components/dialogs/generator-modification-dialog.js, src/components/dialogs/input-hooks.js, src/components/dialogs/line-attach-to-voltage-level-dialog.js, src/components/dialogs/line-creation-dialog.js, src/components/dialogs/line-split-with-voltage-level-dialog.js, src/components/dialogs/load-creation-dialog.js, src/components/dialogs/load-modification-dialog.js, src/components/dialogs/shunt-compensator-creation-dialog.js, src/components/dialogs/two-windings-transformer-creation-dialog.js, src/components/dialogs/voltage-level-creation-dialog.js, src/components/graph/menus/network-modification-node-editor.js
when passing Promise as props for hypothesis dialogs.
=> Rename fetched* variables to *Promise for readiness 

package.json, src/components/network/equipment-table.js, src/components/network/network-table.js
The edited row in the spreadsheet is now always on top of the table.
The table can be scrolled again, but the edited row will still be displayed on top of other rows.
=> Force edited row on top of table

src/components/network/network-table.js
Fixes a bug where the edited row number could change mid edit if columns were sorted. Now, we always search the correct row instead of storing the original row number.
=> Fixes a bug where the edited row number could change mid edit

src/components/network-map-tab.js, src/redux/reducer.js
hack to avoid reload Geo Data when switching display mode to TREE then back to MAP or HYBRID
defaulted to true to init load geo data with HYBRID defaulted display Mode
TODO REMOVE LATER
=> Fix NetworkMapTab : Avoid geo data reload when useless 

src/components/study-container.js
when clicking a switch, we get a memory leak like this: network in
context in
loadNetwork in
context in
updateNetwork in
context in
loadNetwork in
...
update updateNetwork at the same time as loadNetwork in this case (when currentNode is changed shallowly but the id doesn't change) to break the loop (even though updateNetwork doesn't need to be updated)
=> fix memory leak when clicking on a switch

src/components/graph/menus/modification-list-item.js, src/components/graph/menus/network-modification-node-editor.js, src/components/study-container.js
Each new modification (dom element) holds a reference to the network at the time of the click, even though it doesn't use it.
The memory leak looks like
network in
context in
onClick in
props in
children in
__reactProps$d134hf12125 in
divElement in
...
Fix it by not having a network variable in scope when we create the jsx (this is because the reconciler reuses an intermediate div element that doesn't change, which holds references to all the props of the children. onClick itself doesn't use network, it gets a reference to network because it is in the single closure capture context of the scope)
=> fix a network memory leak in NodeEditor when clicking on a switch

package-lock.json
Failed to parse source map from 'node_modules/react-csv-downloader/src/index.tsx' file: Error: ENOENT: no such file or directory, open 'node_modules/react-csv-downloader/src/index.tsx'
https://github.com/dolezel/react-csv-downloader/issues/316
=> Upgrade react-csv-downloader 2.9.0 to remove npm warnings

src/components/graph/menus/network-modification-node-editor.js
refactor(NetworkModificationNodeEditor): generalize adapt usage (which forward the defaultParams) to homogeneize the code
=> Generalize adapt usage in NetworkModificationNodeEditor

src/components/dialogs/generator-creation-dialog.js
fix(GeneratorCreationDialog): voltageRegulationTypeField variant passed to default one (outlined)
=> Fix GeneratorCreationDialog: voltageRegulationTypeField variant

src/components/dialogs/generator-creation-dialog.js
Disables the VoltageSetPoint field when not in use to prevent a validation error if a generator is copied from another.
=> Disables the VoltageSetPoint field when not in use

src/components/dialogs/two-windings-transformer/two-windings-transformer-creation-dialog.js
Manage ratioTap and phaseTap which need to be undefined when switch disabled
=> Fix TwoWindingsTransformerCreationDialog save with ratioTap or phaseTap

src/components/diagrams/networkAreaDiagram/network-area-diagram.js
Temporary fix to prevent the NAD for overlapping the tree when switching from MAP display to HYBRID display.
=> Temporary fix to prevent the NAD for overlapping the tree

src/components/dialogs/two-windings-transformer/phase-tap-changer-pane.js, src/components/dialogs/two-windings-transformer/ratio-tap-changer-pane.js, src/translations/en.json, src/translations/fr.json
- When validating the high tab and low tab values in row generation, check the number of taps instead of the high tap value.
- Change error message
=> Fix tap validation in 2w transformer creation

src/components/dialogs/two-windings-transformer/phase-tap-changer-pane.js, src/components/dialogs/two-windings-transformer/ratio-tap-changer-pane.js
This glitch can be seen when creating a new rule does not change the key of the table in 2W transformer creation dialogue.
Changing the key to string ensure the key is always unique and change each time we create a new rule
=> change tables keys to string to make it unique

src/components/diagrams/singleLineDiagram/single-line-diagram.js
When working on node not built, opening multiple SLD can lead to some of them being displayed out of the screen because we take the size of the last sld,
This PR is to make sure when opening multiple sld and the current node is not built, each sld will be displayed inside the screen.
=> fix sld display when selecting a node not built

src/components/dialogs/generator-creation-dialog.js
Fixes a stuck validation form in the generator creation dialog if the reactive power or the qpercent is incorrectly set and then not used.
=> Generator creation form regression

src/components/diagrams/singleLineDiagram/single-line-diagram-pane.js
regression from e3aa1d9be03d7a39edd88c5d4033a91daad40d92
```
-            sldTitle +=
-                ' \u002D ' +
-                network.getSubstation(displayedSubstation.id).countryName;
+                const substation = network.getSubstation(vlId);
+                const countryName = substation?.countryName;
+                if (countryName) {
+                    name += ' \u002D ' + countryName;
+                }
```
=> fix sld voltagelevel titles, put back country when available

src/components/dialogs/generator-creation-dialog.js
Add optional in the placeholder of startup fields in the generator creation dialog
=> Add optional startup fields

.gitignore
Gitignore the coverage folder created when using unit tests with coverage.
=> Gitignore the coverage folder

src/components/diagrams/diagram-pane.js
Fixes a bug which causes the right displayed diagrams to be displayed on the left of the pane after a window resizing.
=> A NAD could be displayed on the left after window resizing

src/components/network-map-tab.js
geoDataRef is used for positions initialization. The "then" of the fetchSubstationPositions and fetchLinePositions promises are executed without any render between them if the requests finish almost at the same time. So we must set the ref immadiately instead of waiting for the next render. 
=> Fix small network opening

src/components/diagrams/diagram-resizable-box.js
Removes an error message in the console related to ResizableBox
=> Removes an error message in the console related to ResizableBox

src/components/network-map-tab.js, src/components/network/overloaded-lines-view.js
Widens the overloaded line table to prevent some values from being truncated.
=> Widens the overloaded line table

src/components/network/overloaded-lines-view.js
Filtering by overload treshold was broken. This PR fixed it. 
Also the overloaded lines table was not updated after a loadflow. It is fixed.
=> Fix overloaded lines view: fix filter by threshold + fix update after lf

src/components/run-button-container.js
Warning: Failed prop type: Invalid prop `runnable` of type `object` supplied to `RunButtonContainer`, expected an array.
=> Fix RunButtonContainer : runnable to PropTypes.object instead of array.

.github/workflows/build.yml
since new runner image
cf : https://github.com/actions/runner-images/blob/ubuntu22/20230217.1/images/linux/Ubuntu2204-Readme.md
version : 20230217.1/
Our CI/CD github Action fails sometimes
at npm run build step :
```
<--- Last few GCs --->
[1759:0x6ba0f20]   107119 ms: Mark-sweep 1994.2 (2089.2) -> 1979.8 (2090.7) MB, 2184.9 / 0.0 ms  (average mu = 0.267, current mu = 0.024) allocation failure; scavenge might not succeed
[1759:0x6ba0f20]   109898 ms: Mark-sweep 2000.5 (2096.0) -> 1986.3 (2097.2) MB, 2448.2 / 0.0 ms  (average mu = 0.192, current mu = 0.119) allocation failure; GC in old space requested
<--- JS stacktrace --->
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```
should increase our max-old-space-size maybe for Node.js …
=> Fix githubaction node heap out of memory

src/translations/en.json, src/translations/fr.json
Correction after merge PR : https://github.com/gridsuite/gridstudy-app/pull/1131
In case of error on back, the title of snack bar is not translated as bellow
=> Dynamic simulation - lack of translation for fetching errors

src/components/dialogs/parameters/load-flow-parameters.js
to update parameters when `provider` and `defaultValues` changes but not when `lfParams` changes otherwise you enter a loop of `setCurrentParameters` calls
=> Fix Control the effect in SpecificLoadFlowParameters 

src/components/dialogs/parameters/dynamicsimulation/network-parameters.js, src/components/dialogs/parameters/dynamicsimulation/solver/ida-solver-parameters.js, src/components/dialogs/parameters/dynamicsimulation/solver/simplified-solver-parameters.js, src/components/dialogs/parameters/dynamicsimulation/time-delay-parameters.js
Remove the redundant debounces in dynamic simulation parameters after merging PR: https://github.com/gridsuite/gridstudy-app/pull/1274
which generally manages debounce in the hook : useParametersBackend
=> Dynamic Simulation - Parameters - Remove debounce at low level

src/components/dialogs/commons/modificationDialog.js
Remove useless props use in ModificationDialogContent
Warning: Unknown event handler property `onValidationError`. It will be ignored.
Warning: Unknown event handler property `onValidated`. It will be ignored.
=> Fix warning in ModificationDialog

src/components/app-top-bar.js
Stops the silent renew from hiding the parameters dialog, and hide the parameters dialog when the user is logged out.
=> Stops the silent renew from hiding the parameters dialog

src/components/utils/rhf-inputs/error-inputs/error-input.js
Previously, when users submitted a form and there was an error message generated at the bottom, it wasn't immediately visible due to the form's length.
To enhance the user experience, I've implemented an auto-scroll feature.
=> Auto-Scroll to Error Messages on Long Forms

src/components/dialogs/parameters/dynamicsimulation/curve-parameters.js, src/components/dialogs/parameters/dynamicsimulation/curve/dialog/curve-preview.js, src/components/dialogs/parameters/dynamicsimulation/curve/dialog/curve-selector-dialog.js, src/components/dialogs/parameters/dynamicsimulation/curve/dialog/equipment-filter.js, src/components/dialogs/parameters/dynamicsimulation/curve/dialog/model-filter.js
**Bug found by Charly during the emotion migration** => when expand the variable tree box, a partial content at the bottom is hidden. Note that the bug is only produced if reducing the size of the global window, cf demo
**Solution**: add a scrollbar to the dialogue, see demo after fix
**Bonus**: In this PR, switch to CustomAGGrid for some tables in the curve configuration..
=> Dynamic Simulation: add scrollbar to curve selection dialog

src/components/study-drawer.js
Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `StudyDrawer`, expected `object`.
=> Fix StudyDrawer : console warning

src/components/diagrams/diagram-pane.js
In the current version, we can increase the depth of the SLD to an infinite level because the limit on the number of voltage level is not taken into account.
The wrong metadata are used to get the additional metadata from the back.
@FranckLecuyer helped for this PR.
=> Fix the limit on number of voltage level for the SLD.

src/components/results/securityanalysis/security-analysis-result-nmk.tsx
Restore a broken link from the security analysis results (lines) to their voltage level diagram.
=> line links broken in security analysis results

src/components/study-pane.js
This was used before be6b246ffa when we had drawers with transitions and the elements where manually positionned and transitioned between
left: drawerToolbarWidth
left: drawerExplorerWidth + drawerToolbarWidth
left: drawerNetworkModificationTreeWidth + drawerToolbarWidth
=> cleanup, remove unused transition and rename cssclass

src/components/network/network-map.js
this gives it the same behavior as the initial "map loading" overlay
=> map manual refresh, fix overlay zIndex not applied because position is not set

src/components/network/network-map.js
The new version of deckgl/react-map-gl fixes the bug where you could zoom in more than the max zoom. So now we realize that users actually need a higher maxZoom.
We had chosen 12 because this is the limit that triggers the bug where the text label of active power on the map moves away from the arrow on the line so this will give this bug a little more visibility but it's not a blocker.
=> increase map maxZoom 12->14

src/components/menus/dynamic-simulation/dynamic-simulation-event-menu-item.tsx
fix(): return only the titleId which is used un ModificationDialog later and translate
=> Fix DS Title in dialog translation warning

src/components/diagrams/singleLineDiagram/single-line-diagram-content.js, src/components/menus/branch-menu.js, src/components/menus/bus-menu.tsx, src/components/menus/dynamic-simulation/dynamic-simulation-event-menu-item.tsx, src/components/menus/equipment-menu.js
**Produce bug:**
1. Open SLD diagram 
2. Click on a BUS to show the menu, then click on 'Node fault on bus (Dynamic simulation)'
3. The dialogue opened but the menu is not closed.
**Bug demo:**
**Solution:** invoke handle close menu function inside each specific menu
=> Dynamic Simulation - Context menu does not disappear after opening dialog to edit an event

src/components/dialogs/network-modifications/common/properties/property-utils.ts
I choose to use an empty list by default for properties and to not send it to the backend when the (filtered) list is empty.
=> fix(properties): handle empty properties when copying

src/components/network/map-equipments.js
fix(mapEquipments): in reloadImpactedSubstationsEquipments, if  updatedLines Promise throw an error, it called a snackError with empty message. Use SnackInputs type params like others usage
=> Fix: empty snackError

.env
=> Remove EXTEND_ESLINT from environment configuration.

src/components/dialogs/parameters/dynamicsimulation/curve/dialog/equipment-filter.jsx, src/services/study/network.js
Change fetchVoltageLevelsListInfos to fetchVoltageLevelsMapInfos for better data handling and efficiency. Update equipment-filter.jsx to implement new function and handle nominal voltages accordingly.
=> Merge fetch of VL and NV by changing data type

src/components/dialogs/parameters/load-flow-parameters.jsx, src/components/dialogs/parameters/parameters.jsx
When the user has a profile, to reset the parameters the study server deletes and creates new parameters with a new UUID. But if you call updateProvider in parallel, the study server has time to read the deleted parameter ID from the study and tries to update the parameters after they were deleted.
gridstudy-study-server-1                   | org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 : "{"timestamp":"2024-05-07T12:05:40.080+00:00","status":500,"error":"Internal Server Error","message":"No value present","path":"/v1/parameters/c73808c2-b240-4115-bf1b-91afe66efce5/provider"}"
gridstudy-loadflow-server-1                | java.util.NoSuchElementException: No value present
gridstudy-loadflow-server-1                | 	at …
=> Fix lf param reset (param+provider) race condition when user has a profile

src/components/dialogs/network-modifications/voltage-level/creation/voltage-level-creation-dialog.jsx
Fixed a bug in voltage-level-creation-dialog.jsx where COUPLING_OMNIBUS was not being properly handled, now defaults to an empty array.
probably introduced by #2072
=> Fix empty couplingDevices when VL creation by copy

src/services/study/network-map.js, src/services/utils.js
This pull request fixes a null parameter issue in the `getQueryParamsList` function. The issue was causing errors when the function was called with a null parameter. This PR ensures that the function handles null parameters correctly, preventing any potential errors.
=> Fix null param in getQueryParamsList

src/components/dialogs/parameters/sensi/sensitivity-analysis-parameters.jsx
Fixed bug:
When we select a saved sensitivity params, the validate button is disabled and the computations count is not recalculated.
=> Refresh senstivity table in params when select saved params

src/components/spreadsheet/utils/config-tables.js, src/components/spreadsheet/utils/equipement-table-popup-editors.tsx
In this PR, we resolved a bug where changes made to properties column in the spreadsheet persisted even after canceling the edit.
=> Fix properties custom cell editor

src/components/dialogs/network-modifications/battery/modification/battery-modification-dialog.jsx, src/components/dialogs/network-modifications/generator/modification/generator-modification-dialog.jsx, src/components/dialogs/network-modifications/line/modification/line-modification-dialog.jsx, src/components/dialogs/network-modifications/shunt-compensator/modification/shunt-compensator-modification-dialog.jsx, src/components/dialogs/network-modifications/two-windings-transformer/modification/two-windings-transformer-modification-dialog.jsx, src/components/dialogs/network-modifications/voltage-level/modification/voltage-level-modification-dialog.jsx, src/components/dialogs/network-modifications/vsc/modification/vsc-modification-dialog.tsx
fix a bug on modification dialog, 
when modifying an element on an not build node, if coming back to the editor the value disappeared.
=> fix reset for modification dialog

src/components/dialogs/connectivity/branch-connectivity-form.tsx
FIX BUG from the previous PR: https://github.com/gridsuite/gridstudy-app/pull/2243
=> [FIX] Side 2 Connection Position previous values not shown in line modification

src/components/diagrams/diagram-utils.js, src/components/diagrams/networkAreaDiagram/network-area-diagram-content.jsx, src/redux/actions.ts, src/redux/reducer.ts
This is using https://github.com/powsybl/powsybl-diagram-viewer/pull/101
=> Save NAD node movements in the reducer.

src/components/diagrams/diagram-utils.js, src/components/diagrams/networkAreaDiagram/network-area-diagram-content.jsx, src/redux/actions.ts, src/redux/reducer.ts
Reverts gridsuite/gridstudy-app#2275
Needs to wait for the next powsybl-diagram-viewer version
=> Revert "Save NAD node movements in the reducer."

src/components/custom-aggrid/hooks/use-custom-aggrid-comparator-filter.ts
When a user enters a number as filter value whch has 0s after the dot the rounding displayed is wrong : 
12.000 should display "rounding to 0.0001" but it displays "Rounding to the nearest unit"
=> corrects display rounding

src/components/dialogs/parameters/common/limitreductions/columns-definitions.ts
Reverts a previous revert to restore dev (gridsuite/gridstudy-app#2489)
=> Disable developer mode for limit reductions

src/components/dialogs/parameters/loadflow/load-flow-parameters-content.tsx, src/components/dialogs/parameters/loadflow/load-flow-parameters-header.tsx, src/components/dialogs/parameters/loadflow/load-flow-parameters.tsx
fix(LoadFlowParameters): Limit Reduction Tab was out of the developer mode before rhf migration
=> Fix: Restore Limit Reduction Tab out of devMode

src/components/dialogs/parameters/parameters.tsx
The debounce is only used on a field that will be removed soon.
Removing the debounce helps the language and theme change, and fixes an issue where parameters would not be saved if the parent component do not exist after the debounce timer.
=> Remove the useless debounce in useParameterState

src/components/dialogs/contingency-list-selector.jsx
* When opening the favorite window, **don't** fetch on the server if nothing is selected
* Similarly to remove from favorite (see code below), save the contingency list filtered with removed contingency lists in GridExplore instead of always adding new contingencies lists to existing lists.
https://github.com/gridsuite/gridstudy-app/blob/1d98ae7285b7eb922396a609f03483598467a22f/src/components/dialogs/contingency-list-selector.jsx#L144
For the moment, we decided not to support having more than 100 contingency lists so I did not put the contingencies uuids in the body of the request. We anyway have limitations on the server as it's a varchar(4000) in DB and we can't save much more than 100 contingencies in this.
=> Don't save deleted contingencies list when saving favorites

src/components/dialogs/limits/limits-groups-contextual-menu.tsx, src/components/dialogs/limits/operational-limits-groups-tabs.tsx
changes : 
- prevent the user from manipulating limit sets while he is naming one (no duplication or deletion)
- alignement of left icons
- suffix when duplicating a limit set (_COPY)
- base name for new limisets changed from LIMIT_SET to DEFAULT
=> corrections post tests

src/components/result-view-tab.tsx, src/components/result-view-tab.type.ts, src/components/results/use-results-tab.ts
Solves : 
- result-view-tab.tsx
10:1  error  Dependency cycle via ../use-results-tab:15  import/no-cycle
- shortcircuit-analysis-result-tab.tsx
11:1  error  Dependency cycle via components/result-view-tab:9  import/no-cycle
- use-results-tab.ts
9:1  error  Dependency cycle detected  import/no-cycle
=> Fixes result tab deps cycles

src/components/network/network-map-tab.tsx
fix(NetworkMapTab): Sometimes, the tree is loaded quicker than the network map tab component. Then isNetworkModificationTreeUpToDate is true and doesn't changes later.  This avoid a necessary proc of the effect which is necessary to call updateMapEquipmentsAndGeoData. If the effect is called only once then previousCurrentRootNetworkUuid is null and we never initialize geodata and mapEquipments
=> Fix map not loading sometimes

.npmrc, prettier.config.js, tsconfig.json
The Prettier plugin in IDEs ([VSCode](https://github.com/prettier/prettier-vscode/issues/3623), [~IntelliJ~ WebStorm](https://youtrack.jetbrains.com/issue/WEB-71713/Support-for-prettier.config.ts)) don't support the experimental `prettier.config.ts` format.
Reverting to `prettier.config.js` until the plugins support it.
=> Fix Prettier to work with IDE plugins

src/components/results/dynamicsimulation/plot/plotly-series-chart.tsx
**Observation:** a plot is not synced with a zoom action from another plot unless we manipulate (zoom, etc.) at least once on this plot.
**Reason:** the default layout for Xaxis is configured with field 'autorange' = true..
**Solution:** when sync from other plot, we force 'autorange' = false
=> [Dynamic Simulation] Correction for Sync of zoom between plots

src/components/results/dynamicsimulation/common/gridlayout/responsive-grid-layout.tsx, src/components/results/dynamicsimulation/common/visibility-box.tsx
It seems a regression due to the migration of library autosizer
**Observation:** when we have two tabs of plots, and zooming on a plot of the first tab. Switching to the second tab then back to the first => plot is reset and previous zooming is lost.
**Reason:** when AutoSizer computes width and height from a hidden parent component, width and height may be zero and AutoSizer ignore rendering children (regression from new version autosizer)
**Solution:** fortunatly, the recent new version of AutoSizer provides a props to override this behaviour, i.e. doNotBailOutOnEmptyChildren
**Enhancement:** when providing width and height for the GridLayout, we provide a filter to take only valid computed dimensions, otherwise, the previous valid dimensions are taken into account.. This is usefull …
=> [Dynamic Simulation] Prevent plots unmounted when switching tabs

src/components/diagrams/diagram-grid-layout.tsx
fix(DGL): Do not pop because it removes the entry from the original array.
Just check the size without modification of the array.
=> Fix Diagram Grid Layout inconsistent layout at card removal
