.github/workflows/build.yml, package.json
=> Add github actions 

package.json
=> add home_page

src/index.js
No
Bug fix
When application is not host at / like /study-app/ react router does not work anymore. 
[https://github.com/ReactTraining/react-router/issues/5946](https://github.com/ReactTraining/react-router/issues/5946) …
=> Fix react router relative path issue

src/components/create-study-form.js, src/translations/en.json, src/translations/fr.json
=> Optional study description

src/components/create-study-form.js, src/index.js, src/redux/actions.js, src/redux/reducer.js, src/translations/en.json, src/translations/fr.json, src/utils/rest-api.js
=> Remove file extension check

src/components/create-study-form.js
=> Close dialog after study creation

src/components/network/network-explorer.js
=> Add search vl section

src/components/network/network.js
=> Fix unknown positions bug

src/components/app.js, src/components/network/network-explorer.js, src/components/network/network-map.js, src/components/single-line-diagram.js, src/redux/actions.js, src/redux/reducer.js, src/translations/en.json, src/translations/fr.json, src/utils/rest-api.js
=> Add useName instead of Id

src/components/create-study-form.js, src/components/network/network-explorer.js, src/components/network/network-map.js, src/components/study-manager.js, src/translations/en.json, src/translations/fr.json, src/utils/rest-api.js
=> delete study from contextuel menu

package-lock.json, package.json, src/components/app.js, src/components/create-study-form.js, src/components/network-pane.js, src/components/network/geo-data.js, src/components/network/network-explorer.js, src/components/network/network-map.js, src/components/network/network.js, src/components/single-line-diagram.js, src/components/study-manager.js, src/components/study-pane.js, src/components/top-bar.js, src/redux/actions.js, src/redux/reducer.js, src/translations/en.json, src/translations/fr.json
No
feature + refactoring
Code cleaning +
- replace left drawer by a page
- move use name checkbox to top bar
- change voltage level filter style
- refactoring of redux state structure
- split network and geo data
- optimize data loading
- upgrade to material 4.9.5
- add StudyPane component
- sort voltage levels
- improve responsiveness
**Does this PR introduce a breaking …
=> UI refactoring

src/components/network/network-explorer.js, src/components/top-bar.js, src/translations/en.json, src/translations/fr.json
No
Bug fix
Use name is not translated
Use name is managed by i8n framework.
(if any of the …
=> Fix "Use name" i8n

src/index.js
NO
Bug fix
the network doesn't show on the map on edge because flatmap is missing
the network shows on the map
NO
=> fix flatmap on edge

package-lock.json, package.json, src/components/network/network-map.js
Need to move the NavigationControl or else it was not clickable anymore
NO
Feature
deckgl 7.3.6
deckgl 8.0.0
NO
=> upgrade to deckgl 8

src/components/network/network-map.js
NO
Feature
The map always opens centered on france
The map opens centered on the network, with a 5% margin on each side
NO
=> Center map on network

package-lock.json, package.json
NO
Feature
old react-map-gl (doesn't have a fix for the compass icon)
new react-map-gl
NO
The compass icon is not yet fixed as this requires a new deck.gl version or workarounds
=> upgrade to react-map-gl 5.2.3

src/components/app.js
NO
Feature
When browsing to a bad route, the content is empty
When browsing to a bad route, a big error message saying the URL is bad appears
NO
This is mostly useful after #33 …
=> Errorroute

package-lock.json, package.json, src/components/app.js, src/components/network/geo-data.js, src/components/network/network-explorer.js, src/components/network/network-map.js, src/components/network/network.js, src/components/study-pane.js, src/index.js, src/redux/actions.js, src/redux/reducer.js, src/translations/en.json, src/translations/fr.json, src/utils/rest-api.js
No
feature
When a study is open we cannot copy paste the url to another tab to get the same study in the same state.
The url reflects the study state and we can copy paste a study URL.
**Other …
=> Browser study URL copy/paste support

src/components/study-pane.js
No
Bug Fix
urls have ?voltageLeveLId=xxx
urls have ?voltageLevelId=xxx
NO
=> VoltageLeveL -> VoltageLevel

public/index.html
=> index.html: fix favicon in npm start

src/components/single-line-diagram.js, src/components/study-pane.js, src/utils/rest-api.js
NO
Feature
All components load their own data, except <SingleLineDiagram/>
SingleLineDiagram loads its own data
NO
=> Move svg fetching in single-line-diagram

public/index.html
viewport is very not standardized. The behavior depends on the browsers and their versions. our only hope is to use the most common thing to avoid bugs...
NO
refactor
complicated viewport
simple viewport like everyone.
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check …
=> index.html, use a simpler viewport; this is what everyone uses

src/components/study-pane.js
=> Nextvoltagelevel

src/components/single-line-diagram.js
NO
BugFix
Most of the times, there is a little flicker when displaying an svg in firefox
no flicker
NO
=> Fixflicker

src/components/app.js
NO
BugFix
There's a spurious ')' below the app
no ')'
NO
=> fix spurious parenthesis

src/components/app.js, src/utils/authentication/AuthService.js
NO
Bug Fix
refresh page, get logged out
hit back arrow after login, get BAD URL error
refresh page, still logged in
hit back arrow after login, go back to previous site
**Does this PR introduce a breaking change or deprecate an API?** …
=> fix page refresh and back button behaviour

src/components/study-pane.js
Bug fix
This is a issue when F5
This correct behavior is restored
(if any of the questions/checkboxes don't apply, …
=> Correction of the F5/refresh by changing a parameter

src/components/app.js
=> show sigin callback error  message

.github/workflows/build.yml
=> fix CI after github changes

src/components/app.js
=> add a dummy postlogout url for now

src/components/app.js
=> fixup: we are already logged out in the logout-callback

src/utils/authentication/AuthService.js
=> allow user to change issuer after a logout

src/components/app.js, src/redux/actions.js, src/redux/reducer.js, src/utils/authentication/AuthService.js
=> show sigin callback error

src/components/parameters.js, src/components/study-pane.js, src/redux/actions.js, src/redux/local-storage.js, src/redux/reducer.js, src/translations/en.json, src/translations/fr.json, src/utils/rest-api.js
svg bounding box change for negative point of origin
reorganise option in multiples tabs
=> Add settings for labels display

src/components/create-study-form.js, src/components/study-manager.js, src/translations/en.json, src/translations/fr.json
=> Modify the add-study button by a fancy one

src/components/network/nominal-voltage-filter.js, src/components/study-pane.js, src/translations/en.json, src/translations/fr.json
=> Add check all uncheck all to Voltages Level menu

src/translations/en.json, src/translations/fr.json
=> Correction of some errors in the translation files

CHANGELOG.md
=> First version of the study-app CHANGELOG file

src/components/network/network-explorer.js
=> Don't display 'undefined' when the countryName is not available

src/components/create-study-form.js
=> add uuid for cases

src/components/study-manager.js
=> Fix warning

src/components/app.js, src/components/create-study-form.js, src/components/parameters.js, src/components/top-bar.js
=> make parameter window modal

src/components/single-line-diagram.js
Change zoom factor of panZoom component to increase zoom speed
=> Remove scollbars and change zoom speed on voltage level diagram

src/utils/authentication/UserManagerMock.js
In dev mode, you need to click the login button and then refresh the page (or click the button again) to get logged in
=> Fix login in dev, need to refresh page after click on button

src/components/top-bar.js, src/translations/en.json, src/translations/fr.json
=> Static name for the Study-app

public/index.html
=> Replace Grid explorer by Study app

package-lock.json, package.json, src/components/app.js, src/components/create-study-form.js, src/components/top-bar.js, src/translations/en.json, src/translations/fr.json
=> Full screen mode

src/components/top-bar.js
=> Close menu on full screen option click

src/utils/rest-api.js
=> Fix Authorization header

src/components/single-line-diagram.js
=> Also allows disconnector and load break switch position change

package-lock.json, package.json
=> Upgrade create react app to 3.4.1

src/components/network/layers/arrow-layer-fragment.glsl.js, src/components/network/layers/arrow-layer-vertex.glsl.js, src/components/network/layers/arrow-layer.js
For Edge, Safari compatibility which does not support WebGL v2
=> Port to WebGL v1

src/components/network/network-map.js, src/components/study-pane.js
=> fix arrowsZoom, bump it up a little

CHANGELOG.md
=> Changelog for v0.4.0

src/components/app.js, src/components/top-bar.js
=> Make top bar more independant 

src/components/app.js, src/components/top-bar.js
=> extract on logo clicked from TopBar

src/components/network/line-layer.js, src/components/parameters.js, src/translations/en.json, src/translations/fr.json
=> 2 arrows mode (#146)

src/components/network/line-layer.js, src/components/network/network-map.js, src/components/network/substation-layer.js
=> Same size for all network map labels

src/components/network/line-layer.js
=> Fix bug: arrows disappear when start load flow 

src/components/network/geo-data.js
=> Try to improve the precision of the position of power labels next to arrows

src/components/network/line-layer.js
=> Put power labels above arrows

package-lock.json, package.json
=> change commons-ui version

src/components/network/line-layer.js
=> Use isTerminalConnected data

src/components/parameters.js, src/components/study-pane.js, src/redux/actions.js, src/redux/local-storage.js, src/redux/reducer.js, src/utils/rest-api.js
Modified parameters default values.
Removed topological coloring parameter.
Signed-off-by: NOIR Nicolas ext <nicolas.noir@rte-france.com>
=> Streamline the GridStudy options

src/utils/rest-api.js
=> Escape query string parameters in rest-api.js

src/utils/authentication/UserManagerMock.js
=> Add email to demo user

src/components/network/geo-data.js
=> Correction of the getDistance usage, and the retreival of the line positions when it is inverted

src/translations/en.json, src/translations/fr.json
=> remove unused traduction keys

src/utils/rest-api.js
=> Force queries to pass through the gateway service

src/components/study-manager.js
window.location.href = url;
works but break if an error occurs
=> add an iframe to download grid

app-httpd.conf
=> remove direct API access on builds

app-httpd.conf
=> fixup, broke all backend api calls

src/components/app.js
=> don't silentlogin if user already connected

src/translations/fr.json
=> Fix label for study creation

.env, src/utils/dialogs.js, src/utils/rest-api.js
=> fix export format

src/components/study-pane.js
=> Fix the loadflow button (regression from 48343062cf0 fix warnings)

.prettierrc.json
=> prettierrc: removetrailingComma, we use the default value

src/utils/dialogs.js, src/utils/rest-api.js
The token is now in the url of the export function (fix issue #209)
=> Added the token in the export url

app-httpd.conf, package-lock.json
=> remove spaces

package-lock.json, package.json
=> use commons-ui 0.5.1

src/components/create-study-form.js, src/components/loader-with-overlay.js, src/components/study-manager.js, src/components/study-pane.js, src/redux/actions.js, src/redux/reducer.js, src/utils/rest-api.js
=> Add overlay and loader for the inprogress study

src/components/network/network-map.js, src/components/network/nominal-voltage-filter.js, src/components/study-pane.js, src/redux/actions.js, src/redux/reducer.js
Make the nominal voltage levels filtering persistent after a load flow
=> Make VL filtering persistent after a LF

src/components/single-line-diagram.js
Addition o a progress bar while loading a substation svg
=> Added a progress bar while loading a substation svg

src/components/app.js, src/components/network/network-map.js, src/components/network/network-table.js, src/components/study-manager.js, src/components/study-pane.js
=> Fix warnings

src/components/single-line-diagram.js, src/components/study-pane.js
Prevent topology modification during a loadflow.
=> Prevent topology modification during a computation (LF&AS)

src/components/loader-with-overlay.js, src/components/study-manager.js, src/components/study-pane.js
=> Fix scroll in study page

src/components/single-line-diagram.js, src/components/study-pane.js
US : https://dev.azure.com/gridsuite/MVP/_sprints/backlog/MVP%20Team/MVP/Sprint%2017?workitem=298
=> improve design sld display

src/components/network/line-layer.js, src/utils/colors.js
=> Adapt arrow speed to line loading factor

src/components/network/network-explorer.js, src/components/parameters.js, src/components/single-line-diagram.js, src/components/study-pane.js, src/redux/actions.js, src/redux/local-storage.js, src/redux/reducer.js, src/translations/en.json, src/translations/fr.json, src/utils/rest-api.js
This PR must be merged after : 
https://github.com/gridsuite/study-server/pull/52
https://github.com/powsybl/powsybl-single-line-diagram-server/pull/38
=> Add diagram for substations

src/components/app.js
=> Fix auth on azure: only signinSilent if not in the iframe

package-lock.json, package.json
=> Update commons-ui package to v0.5.2

src/components/network/network-explorer.js, src/components/study-pane.js
draw drawer under loading screen
#	src/components/network/network-explorer.js
#	src/components/study-pane.js
=> fix scroll jump on clik

src/components/single-line-diagram.js
Arrow are now not showing if it links to the same svg and TWT are now navigable.
=> fix navigation arrows

src/utils/rest-api.js
=> fetch apps-metadata: backendFetch -> fetch

src/components/network/network-explorer.js, src/components/single-line-diagram.js, src/components/study-pane.js, src/redux/actions.js, src/redux/reducer.js
=> Add highlight voltage level

src/components/single-line-diagram.js
=> Fix pan in single line diagram

src/components/security-analysis-result.js, src/components/util/virtualized-table.js
=> add sorting to security analysis table

src/components/network/network-explorer.js, src/components/study-pane.js
=> New icon for collapse

src/components/network/network-table.js
=> Fix style input search

src/utils/rest-api.js
=> Fix env.json loading

src/components/single-line-diagram.js
=> fix polyline stealing mouse events

public/index.html, src/components/app.js, src/components/loader-with-overlay.js, src/components/loadflow-result.js, src/components/network/network-explorer.js, src/components/network/network-table.js, src/components/run-button.js, src/components/security-analysis-result.js, src/components/single-line-diagram.js, src/components/study-pane.js, src/components/util/split-button.js, src/index.css
=> Fix scroll

src/components/single-line-diagram.js
=> Add workaround for chromium 78

src/components/app.js
=> fix tremors with scrollbars when sld in fullscreen for some screen sizes

src/translations/fr.json
=> fix typo in fr message for rename

src/components/parameters.js
The overload alert threshold slider availability depends on other configuration parameters values (line flow color mode and display overload table)
=> Correction of overload alert threshold slider availability

src/components/create-study-form.js, src/components/study-manager.js
create a dummy card when creating new study
=> create a dummy card when creating new study

src/components/study-pane.js, src/translations/en.json, src/translations/fr.json
=> Fix SLD switch open/close preview

src/components/network/equipment-table.js, src/components/security-analysis-result.js, src/translations/en.json, src/translations/fr.json
=> lazy loading fix label

package.json, src/components/app.js, src/components/network/network-table.js, src/components/parameters.js, src/components/study-manager.js, src/redux/local-storage.js, src/translations/en.json, src/translations/fr.json, src/utils/messages.js
…
Signed-off-by: Slimane AMAR <slimane.amar@rte-france.com>
=> Generalization (header optional) of 'displayErrorMessageWithSnackbar'  function

src/components/loadflow-result.js, src/translations/en.json, src/translations/fr.json
=> Migrate to PowSyBl Core 4.2.0

src/components/network/network.js, src/components/study-pane.js
After a load flow has been run, the lines transit values are not refreshed.
=> Network not correctly refreshed after loadflow

src/components/network/config-tables.js
=> Fix regression on phase shifter tap modification

src/components/security-analysis-result.js
=> Fix missing nmkSelection button in security analysis result

src/components/single-line-diagram.js
=> fix cursor on svg label

src/components/network/overloaded-lines-view.js
#	src/components/network/equipment-table.js
=> fix cursor on overloaded-lines-view.js

src/components/app-top-bar.js, src/components/app.js, src/components/study-pane.js, src/redux/actions.js, src/redux/reducer.js
=> fix result badges

src/components/network/config-tables.js, src/components/network/equipment-table-editors.js, src/components/network/equipment-table.js, src/translations/en.json, src/translations/fr.json, src/utils/rest-api.js
get limits for tap changer & generator
=> use select for tap changer modification

src/components/network/network-explorer.js
=> fix missing search on tab change

src/components/network/equipment-table.js
=> use ellipsis for truncated fields,

src/components/network/network-table.js
=> limit search on displayed columns

src/components/security-analysis-result.js
=> Upgrade to powsybl 4.3.1

package-lock.json, package.json, src/components/single-line-diagram.js
=> upgrade svg.panzoom.js to fix panzoom margins and fix margins for big svgs

src/translations/en.json, src/translations/fr.json
=> fix studyNotFound

src/components/study-pane.js, src/translations/en.json, src/translations/fr.json, src/utils/rest-api.js
=> replace studyNotFound by real reason of failure

src/utils/rest-api.js
=> Fix URLs after REST API normalization in directory-server

src/components/network/network.js
=> Fix vl remove

src/components/network/network.js
=> Fix voltage levels autocomplete

src/components/network-map-tab.js
=> fix menus in network-map-tab.js

package-lock.json, package.json
=> Use commons UI v0.16.0 (equipment search fix)

src/components/dialogs/input-hooks.js, src/components/dialogs/shunt-compensator-creation-dialog.js, src/translations/en.json, src/translations/fr.json
=> fix front end validation on linear shunt creations

src/components/dialogs/connectivity-edition.js, src/components/dialogs/generator-creation-dialog.js, src/components/dialogs/input-hooks.js, src/components/dialogs/line-creation-dialog.js, src/components/dialogs/load-creation-dialog.js, src/components/dialogs/network-modifications-dialog.js, src/components/dialogs/shunt-compensator-creation-dialog.js, src/components/dialogs/two-windings-transformer-creation-dialog.js, src/components/graph/menus/network-modification-node-editor.js
There is a crash occuring when editing connectivity for a network modification which was not already built.
=> Fix crash in connectivity edition for a network modification

src/components/util/text-field-with-adornment.js
=> US 709 voltage level creation, post FuncRev 2

src/components/graph/util/node-single-double-click-hook.js
=> fix modifications tree rerender

src/components/study-pane.js
=> Fix modifications panel overflow

src/components/study-pane.js
=> fix study pane heigth

package-lock.json, package.json
=> upgrade to commons ui 0.17.0

src/components/study-pane.js
=> Fix study pane vibrations

src/components/network-modification-tree.js
=> Adjust tree focus when we open or close the modifications pane

src/components/util/waiting-loader.js
=> fix(WaitingLoader): remove isRequired for children props

src/components/network-modification-tree.js
=> Fit tree view on load

src/components/dialogs/generator-creation-dialog.js, src/components/dialogs/load-creation-dialog.js
=> Fix form fields to double

src/components/menus/equipment-menu.js, src/components/network-map-tab.js, src/components/network/network-map.js
=> fix equipment right click menu

package-lock.json, package.json, src/components/dialogs/dialogUtils.js, src/components/dialogs/input-hooks.js, src/components/dialogs/load-creation-dialog.js, src/translations/fr.json
=> minor fixes on searchElementDialog

src/components/dialogs/input-hooks.js
=> small fixes on forms

src/index.css
=> Migrate to PowSyBl 4.6.1

src/components/dialogs/network-modifications-dialog.js
=> fix network-modification-dialog, add left alignment for multiline text

src/components/network-map-tab.js
=> fix geo data errors message

src/components/dialogs/form-search-copy-hook.js, src/components/dialogs/generator-creation-dialog.js, src/components/dialogs/input-hooks.js, src/components/dialogs/line-creation-dialog.js, src/components/dialogs/load-creation-dialog.js, src/components/dialogs/shunt-compensator-creation-dialog.js, src/components/dialogs/substation-creation-dialog.js, src/components/dialogs/two-windings-transformer-creation-dialog.js, src/components/dialogs/voltage-level-creation-dialog.js, src/translations/en.json, src/translations/fr.json, src/utils/rest-api.js
=> copy equipment

src/components/network-map-tab.js, src/components/study-pane.js
=> Fix centering on substation after manual panning

src/components/graph/menus/network-modification-node-editor.js, src/components/util/checkbox-list.js
=> fix scrollbar on network-modification-node-editor.js

src/components/graph/menus/network-modification-node-editor.js
=> move equipment modification toolbar above modification count

src/components/dialogs/line-creation-dialog.js
=> Fix line creation edition: bug when empty current limits

src/components/dialogs/generator-creation-dialog.js
=> Fix copy equipment

src/components/dialogs/shunt-compensator-creation-dialog.js
=> fix mcs update translation

src/components/graph/menus/modification-list-item.js, src/components/graph/menus/network-modification-node-editor.js, src/translations/network-modifications-en.json, src/translations/network-modifications-fr.json
=> add translation for open / close switch

src/components/network/equipment-table-editors.js
=> Fix tap selectors to show the right amount of elements

src/components/network/config-tables.js, src/translations/en.json, src/translations/fr.json
=> Add target Q value to generators spreadsheet and apply convention to q value for batteries

package-lock.json, package.json
=> commons-ui v0.20.5

src/components/app-top-bar.js
update style of node name in topbar
=> update style of node name in topbar

src/components/graph/menus/create-node-menu.js, src/translations/en.json, src/translations/fr.json
=> Replace After/Before by Below/Above and remove unused translation keys

src/components/network/substation-layer.js
=> fix substation label position

package-lock.json, package.json
=> upgrade diagram viewer to v0.1.2

src/components/diagrams/singleLineDiagram/single-line-diagram-pane.js
Fixes an issue when trying to open a minimized SLD
=> Fixes an issue when trying to open a minimized SLD

src/components/parameters.js, src/translations/en.json, src/translations/fr.json
Updates labels for new loadflow parameters
=> Label updates

src/components/graph/menus/editable-title.js
- add tooltip and fix style of nodeName in modification panel
Signed-off-by: Ahmed Ben Daamer [ahmed.bendaamer@rte-france.com]
=> add tooltip and fix style of nodeName in modification panel

src/components/app-top-bar.js, src/components/network-modification-tree.js, src/redux/reducer.js
* show selected node in topbar
* no default root node pre-selected
* synchronise the nodename in topbar with all events on the  selected node (update node name , delete node ...)
=> show selected node in topbar

package-lock.json, package.json
=> commons-ui v0.21.0

src/components/diagrams/networkAreaDiagram/network-area-diagram-pane.js, src/components/diagrams/networkAreaDiagram/network-area-diagram.js, src/components/diagrams/singleLineDiagram/single-line-diagram.js, src/components/study-pane.js
Network Area Diagram is now on the right side of the screen.
Minor visual improvements.
=> Network Area Diagram is now on the right side of the screen

src/utils/rest-api.js
=> fix nad error display

src/components/dialogs/input-hooks.js, src/components/graph/menus/modification-list-item.js, src/components/graph/util/center-graph-button.js, src/components/horizontal-toolbar.js, src/components/network-modification-tree.js, src/translations/en.json, src/translations/fr.json, src/utils/UIconstants.js
Signed-off-by: anas-drissi <anas.drissi@rte-france.com>
=> add tooltip for tree buttons

package-lock.json, package.json
=> Update commons-ui to v0.22.0

src/components/diagrams/networkAreaDiagram/network-area-diagram.js, src/components/study-pane.js
The NAD will not be displayed on top of the SLD anymore.
=> Improves the NAD display when SLDs are open.

src/components/graph/nodes/network-modification-node.js, src/components/network-modification-tree.js
=> remove built_invalid

src/components/graph/menus/network-modification-node-editor.js
=> fix Drag and Drop of Network modifications list + feat Move progession status in subtitle

src/components/diagrams/singleLineDiagram/single-line-diagram-pane.js
All visible SLD are updated now.
=> fix display of pinned SLDs

package-lock.json, package.json
=> Use commons-ui v0.22.1

src/components/graph/menus/network-modification-node-editor.js, src/translations/network-modifications-en.json, src/translations/network-modifications-fr.json
Refactor some code for lisibility and add some comments
=> Fix(NetworkModificationNodeEditor): Clear modifications List only when needed

src/components/diagrams/singleLineDiagram/single-line-diagram-pane.js, src/components/study-pane.js
Fixes the SLD from disappearing when the current node is not built and we change tab.
=> Fixes the SLD from disappearing

src/components/menus/line-menu.js
=> fix line menu disabled

package-lock.json, package.json
=> Use commons-ui v0.23.0

src/components/app-wrapper.js, src/components/app.js
=> Add CardErrorBoundary

src/utils/rest-api.js
=> Fix ws urls: use latest token instead of a potentially expired one

src/components/study-pane.js
=> Fix spurious 0 in dom preventing 100% fullscreen of slds

src/components/dialogs/parameters/load-flow-parameters.js, src/components/dialogs/parameters/parameters.js
=> fix loadflow panel

src/components/diagrams/singleLineDiagram/single-line-diagram-pane.js
=> Minimized sld can be reopened from map view

src/components/graph/network-modification-tree-model.js, src/components/graph/util/model-functions.js, src/components/network-map-tab.js, src/components/network-modification-tree.js, src/components/study-container.js
=> Fix: disable updateNetwork and updateGeoData on currentNode renaming

src/components/graph/menus/modification-list-item.js
hide temporarily the possibility of editing hypothesis throught the update button
=> hide edition on hypothesis

src/components/study-container.js
=> Pinned SLD are not minimized anymore when changing node

package-lock.json, package.json
=> Use commons-ui v0.24.1

src/components/dialogs/generator-creation-dialog.js, src/components/dialogs/input-hooks.js, src/components/dialogs/line-creation-dialog.js, src/components/dialogs/load-creation-dialog.js, src/components/dialogs/shunt-compensator-creation-dialog.js, src/components/dialogs/two-windings-transformer-creation-dialog.js, src/components/graph/menus/network-modification-node-editor.js, src/utils/rest-api.js
=> fetch voltage level from back when creating network modif

src/components/app.js, src/components/network/config-tables.js, src/components/network/network-table.js
This US contains various fixes, then please refer to US description.
A special point of attention: to reset the filter value (not the regexp itself, but the string/input value), I had to use a "useRef": please tell me if there is a better way.
=> Us 978 tableur corrections diverses

src/components/app-top-bar.js, src/components/dialogs/equipment-search-dialog.js, src/utils/UIconstants.js
between searchMatchingEquipments callings (between keyboard inputs)
=> Add a 1s timeout before fetching equipments infos 

src/components/dialogs/generator-modification-dialog.js, src/components/dialogs/line-attach-to-voltage-level-dialog.js, src/components/dialogs/line-split-with-voltage-level-dialog.js, src/components/dialogs/load-modification-dialog.js, src/components/dialogs/voltage-level-creation-dialog.js, src/components/graph/menus/network-modification-node-editor.js, src/utils/rest-api.js
=> Fix substations and lines relative to node in forms

src/components/app-wrapper.js, src/components/network/equipment-table.js, src/components/network/network-table.js
When there is scrollbar in the spreadsheet, the selected equipment  is displayed at the top with different background color .
If there is no scrollbar, the selected equipment just change the background color.
=> auto scroll to selected row

src/components/dialogs/generator-modification-dialog.js, src/components/dialogs/load-modification-dialog.js, src/components/graph/menus/network-modification-node-editor.js
=> Code cleaning after hypothesis improvment

src/components/app-top-bar.js, src/components/dialogs/equipment-search-dialog.js, src/components/util/search-matching-equipments.js
=> Pool searchMatchingEquipments

src/components/dialogs/parameters/load-flow-parameters.js, src/components/dialogs/parameters/parameters.js
=> Control showAdvancedParams in Parameter component

src/components/diagrams/networkAreaDiagram/network-area-diagram-pane.js, src/components/diagrams/networkAreaDiagram/network-area-diagram.js, src/components/study-pane.js
=> standardize nad and sld

src/components/diagrams/singleLineDiagram/single-line-diagram.js, src/components/network-map-tab.js, src/components/network/network-table.js
Signed-off-by: Franck LECUYER <franck.lecuyer@rte-france.com>
=> Restore read-only mode for root node

package-lock.json, package.json, src/components/diagrams/networkAreaDiagram/network-area-diagram.js
=> Use powsybl-diagram-viewer 0.1.3

src/components/dialogs/form-search-copy-hook.js, src/components/dialogs/parameters/load-flow-parameters.js, src/components/dialogs/parameters/map-parameters.js, src/components/dialogs/parameters/network-parameters.js, src/components/dialogs/parameters/parameters.js, src/components/dialogs/parameters/single-line-diagram-parameters.js, src/components/directory-item-selector.js, src/components/graph/util/model-constants.js, src/components/network-map-tab.js, src/components/network/equipment-table-editors.js, src/components/network/equipment-table.js, src/components/network/layers/arrow-layer-fragment.glsl.js, src/components/network/layers/arrow-layer-vertex.glsl.js, src/components/result-view-tab.js, src/components/run-button-container.js, src/components/util/is-object-equals.js, src/components/util/list-item-with-delete-button.js, src/components/util/loader-with-overlay.js, src/components/util/virtualized-table.js, src/setupProxy.js, src/setupTests.js
Add missing header in source files
=> add missing header

src/components/network/config-tables.js, src/components/network/equipment-table-editors.js, src/components/network/network-table.js, src/translations/en.json, src/translations/fr.json, src/utils/rest-api.js
We also want to do it using the 'Update Load' existing hypothesis rather than a generic groovy update.
=> Add new editable fields in the LOADS tab in the spreadsheet : name, type, p0, q0.

package-lock.json, package.json, src/components/app-top-bar.js
Wait for next commons-ui release
=> Read only mode for search dialog (for tree node not built)

src/components/dialogs/export-dialog.js
=> useMeta hook exported to commons-ui project

src/utils/rest-api.js
Signed-off-by: Slimane AMAR <slimane.amar@rte-france.com>
=> Fix encoding slash for voltage level ids

package-lock.json, package.json
=> Use commons-ui v0.26.1

src/translations/fr.json
Signed-off-by: TAILASSAN Mehdi Ext <tailassanmeh@gm0winl459.bureau.si.interne>
=> feat: update tree tooltip label in french

src/components/dialogs/generator-modification-dialog.js, src/components/network/network.js
Delete the new fields added to generator creation dialogue from generator modification dialogue
=> Delete fields in generator modification

src/components/dialogs/parameters/parameters.js
=> Fix parameter panel

src/components/dialogs/parameters/parameters.js
=> Set advanced parameters in last tab

package-lock.json, package.json, src/components/app.js, src/redux/actions.js, src/redux/reducer.js, src/utils/rest-api.js
=>  Manage unauthorized user connection alert

package-lock.json, package.json
=> Use commons-ui v0.27.1

src/components/dialogs/equipment-deletion-dialog.js, src/components/dialogs/inputs/use-autocomplete-field.js, src/components/graph/menus/modification-list-item.js, src/components/graph/menus/network-modification-node-editor.js, src/utils/rest-api.js
Add the possibility to edit an equipment deletion.
Few code cleaning.
=> Add the possibility to edit an equipment deletion.

src/components/diagrams/networkAreaDiagram/network-area-diagram-pane.js
=> Fix: Avoid update svgUrl when nothing is displayed

.github/workflows/build.yml, src/components/study-container.js, src/translations/en.json, src/utils/rest-api.js
=> study deletion notif refactoring

src/components/dialogs/dialogUtils.js
=> Fix slider default value

src/components/dialogs/parameters/parameters.js
=> Hide shortcircuit parameters when developer mode off

src/components/dialogs/dialogUtils.js
=> Revert bad fix on slider

package-lock.json, package.json, src/components/app.js, src/redux/reducer.js
=> Use authenticationRouterError from commonsui

src/components/dialogs/two-windings-transformer/two-windings-transformer-creation-dialog.js
Signed-off-by: TOURI ANIS <anis-1.touri@rte-france.com>
=> fix validation activation

src/components/graph/menus/network-modification-node-editor.js
refactor(NetworkModificationNodeEditor): use withEquipmentModificationOptions with adapt
=> Refactor NetworkModificationNodeEditor to generalize adapt using

src/components/graph/menus/network-modification-node-editor.js
=> Fix SubstationCreationDialog doesn't need withVLs Promise

src/components/dialogs/line-attach-to-voltage-level-dialog.js, src/components/dialogs/line-split-with-voltage-level-dialog.js
=> Fix remove onCancel it doesn't exist anymore

src/components/dialogs/two-windings-transformer/two-windings-transformer-creation-dialog.js
=> Fixes error in previous merge

src/components/graph/menus/modification-list-item.js
Signed-off-by: Slimane AMAR <slimane.amar@rte-france.com>
=> Fix : prevent editability of line status modification

src/components/dialogs/two-windings-transformer/phase-tap-changer-pane.js, src/components/dialogs/two-windings-transformer/two-windings-transformer-creation-dialog.js, src/translations/en.json, src/translations/fr.json
=> Check the "alpha" instead of "ratio" column for phase tap changer

src/utils/rest-api.js
Signed-off-by: Slimane AMAR <slimane.amar@rte-france.com>
=> Fix status line modification refactoring

src/components/dialogs/inputs/reactive-capability-curve-table.js, src/components/dialogs/reactive-capability-curve-reactive-range.js
=> Change the labels of the generator reactive limits diagram table

src/components/dialogs/generator-creation-dialog.js, src/translations/en.json, src/translations/fr.json
=> Remove the limits for the active power setpoint field in group creation

src/components/diagrams/singleLineDiagram/single-line-diagram.js
=> Refresh zoom on sld resizing to prevent the app from exceeding min/max zoom

src/components/dialogs/form-search-copy-hook.js
=> Close search form after an equipment is selected

src/components/diagrams/singleLineDiagram/single-line-diagram.js
=> Fix error message when attaching lines to splitting lines while SLD is open

src/components/dialogs/two-windings-transformer/two-windings-transformer-creation-dialog.js
=> Activate the validate button of phase tap changer when its table change

src/components/diagrams/singleLineDiagram/single-line-diagram.js, src/index.css
Signed-off-by: walid-sahnoun <walid.sahnoun@rte-france.com>
=> Fix SLD invalid values

src/components/study-container.js
=> Hide error message when attaching lines while SLD is open

src/components/dialogs/line-split-with-voltage-level-dialog.js, src/components/dialogs/lines-attach-to-split-lines-dialog.js
=> Change line split and line attach fields labels

src/components/dialogs/inputs/use-expandable-values.js
Larger button for "Add value" label
=> fix:use all line for add value button

src/components/network-map-tab.js, src/components/network/map-equipments.js
Signed-off-by: walid-sahnoun <walid.sahnoun@rte-france.com>
=> fix map display on root node at startup

src/components/dialogs/generator-modification-dialog.js
=> Modify Generator modification regulation type field

src/translations/fr.json
Signed-off-by: bendaamerahm <ahmed.bendaamer@rte-france.com>
=> update message translation

src/components/dialogs/parameters/short-circuit-parameters.js, src/translations/en.json, src/translations/fr.json
Signed-off-by: walid-sahnoun <walid.sahnoun@rte-france.com>
=> remove shortcircuit params

src/components/diagrams/networkAreaDiagram/network-area-diagram.js, src/utils/rest-api.js
Signed-off-by: TOURI ANIS <anis-1.touri@rte-france.com>
=> Homogenize NAD/SLD returns

src/components/network/network-map.js
=> Fix LineLayer onHover tooltip following pointer

src/components/study-container.js
=> Fix the error message when a study is renamed.

src/components/network-map-tab.js
=> Fix geo data update

package-lock.json, package.json
=> upgrade to powsybl diagram viewer v0.1.7

src/components/network-map-tab.js, src/components/study-container.js
=> Update flows on map after LF

package-lock.json, package.json
=> Upgrade to powsybl-diagram-viewer v0.1.8

src/components/result-view-tab.js
Signed-off-by: bendaamerahm <ahmed.bendaamer@rte-france.com>
=> fix shortcircuit analysis results tab

src/components/study-container.js
=> Remove notification log

src/components/network-map-tab.js, src/components/study-container.js
=> Fix equipment deletion : change attribute names

src/components/diagrams/diagram-pane.js, src/components/util/sort-functions.js, src/components/util/sort-functions.test.js, src/components/util/validation-functions.test.js
Diagrams can now be aligned to the left or right of the screen independently of their type.
=> Diagrams can now be aligned to the left or right

src/redux/reducer.test.js
=> Some unit tests for the reducer.

src/components/diagrams/diagram-common.js, src/components/diagrams/diagram-resizable-box.js, src/components/diagrams/diagram.js
=> Refactoring of the resizableBox used in diagrams.

src/components/network-map-tab.js
=> Fix map loader after LF

src/translations/fr.json
Equipartition -> Equirépartition
=> fix load/generator scaling : fr tranlsation change

src/translations/fr.json
Replace the french translation of "equipment" from ""equipement" to "ouvrage"
=> Replace the french translation of "equipment"

src/components/run-button-container.js
When we change the node from a failed node, we need to update the status and display the new status accordingly.
=> fix update status when we change node and back ko

src/components/dialogs/export-dialog.js, src/components/dialogs/parameters/load-flow-parameters.js, src/components/dialogs/parameters/parameters.js
Move states where needed
Add some useRef to control effect processing
Rename AdvancedParameterButton -> SubgroupParametersButton
=> fix(parameters): Avoid multiple providers fetch calls

src/components/dialogs/parameters/dynamicsimulation/curve-parameters.js, src/components/dialogs/parameters/dynamicsimulation/mapping-parameters.js, src/components/dialogs/parameters/dynamicsimulation/solver-parameters.js
Use nullish operator ?? when de-structuring a possible nullish value.
=> Dynamic Simulation - Avoid crash in tab Dynamic Simulation of parameters while dynamic mapping server is not available

src/components/dialogs/parameters/dynamicsimulation/curve/common/checkbox-treeview.js, src/components/dialogs/parameters/dynamicsimulation/curve/dialog/equipment-filter.js, src/components/dialogs/parameters/dynamicsimulation/curve/dialog/model-filter.js
Test with network nordic
- model name is wrapped when too long
- scrollbar not shown correctly
- voltage levels and equipment not shown when name absence in network
**Before** 
**After**
=> Dynamic Simulation - Correct some visual bugs in curve parameters

src/components/dialogs/network-modifications/generator/modification/generator-modification-dialog.js
Fixes the minimum active power test relative to the maximum active power in the generator modification form.
=> Fixes the minimum active power test 

src/components/graph/menus/create-node-item.js, src/components/graph/menus/create-node-menu.js, src/components/menus/base-equipment-menu.js, src/components/menus/branch-menu.js
Remove useless savage CSS classes
Remove useless <div>
Use FormattedMessage component when possible instead of intl
Tests done : 
Contextual Nested Menu in tree
Contextual Nested Menu in Map
=> Recursive version to build node nested contextual menu

src/components/dialogs/parameters/parameters.js
Add debounce for other parameters in app.
=> fix debounce fetch always after setState to keep reactivity

src/components/graph/menus/network-modification-node-editor.js
Add node deleted notification consumption to manage modifications clipboard reset.
This clipboard needs to be cleaned when those modifications came from the newly deleted node.
=> Fix NetworkModificationNodeEditor : Clean modifications clipboard when origin node is removed

src/components/graph/menus/create-child-menu-item.js, src/components/graph/menus/network-modification-node-editor.js, src/components/graph/menus/network-modifications-menu.js
I chose the spread way to Initialize an Array with Conditional Elements
cf https://codeburst.io/3-ways-to-initialize-an-array-with-conditional-elements-in-javascript-c95397615a7e
=> Pass SHUNT_COMPENSATOR_MODIFICATION into developer mode

src/components/dialogs/network-modifications/line/modification/line-modification-dialog.js, src/components/dialogs/network-modifications/two-windings-transformer/modification/two-windings-transformer-modification-dialog.js
Fixes the isDirty flag when selecting an equipment with temporary current limits in the line and 2wt modification forms.
=> Fixes the isDirty flag line-modification and 2WT-modification

src/components/results/shortcircuit/shortcircuit-analysis-result-table.tsx, src/components/security-analysis-result.js
Optimize groupPostSort N² complexity to N.
=> Fix CustomAGGrid:postSortRows : optimize groupPostSort

src/components/app-top-bar.js, src/components/diagrams/diagram-footer.js, src/components/menus/base-equipment-menu.js, src/components/results/dynamicsimulation/dynamic-simulation-result-chart-tabs.js, src/components/results/dynamicsimulation/dynamic-simulation-result-table.js, src/components/spreadsheet/columns-config.js
Emotion migration, new batch of files.
=> Emotion make styles batch2

src/components/spreadsheet/table-wrapper.js
Fix suite au merge entre temps de la PR : https://github.com/gridsuite/gridstudy-app/pull/1479
=> Fix modification type generated from voltage modification in spreadsheet

src/components/utils/dnd-table/dnd-table.js
=> Adds a discreet border to the DND table

src/components/dialogs/parameters/parameters.js, src/components/dialogs/parameters/sensi/sensitivity-Flow-parameters.tsx, src/components/dialogs/parameters/sensi/sensitivity-analysis-parameters.js
This PR should be merged in the `move-custom-param-sensi-to-window-parameter` branch after these two PR are merged into `main` : 
- https://github.com/gridsuite/gridstudy-app/pull/1522
- https://github.com/gridsuite/gridstudy-app/pull/1561
=> Emotion migration for impacted file of sensi param migration.

src/components/diagrams/diagram-common.js
Fixes a warning in the console related to kebab-case of CSS definition.
=> Fixes a warning in the console related to kebab-case of CSS definition.

src/components/dialogs/parameters/parameters.js
Align dialog from top of the viewport
Disallow dialog closing when backdropClick or escapeKeyDown
=> Parameters: Align dialog from top of the viewport and disallow backdropClick or escapeKeyDown

src/components/dialogs/network-modifications/voltage-level/modification/voltage-level-modification-dialog.js, src/components/spreadsheet/table-wrapper.js
handle nullable identifiableShortCircuit
=> Fix voltage level modification

src/components/dialogs/set-points/set-points-utils.js, src/components/spreadsheet/utils/config-tables.js
allow null spetpoint in groupe modification
add min/max controls in the spreadseet for batteries
=> fix controls not done on batterie spreadsheet

src/components/dialogs/connectivity/connectivity-form-utils.js, src/components/dialogs/network-modifications/line-attach-to-voltage-level/line-attach-to-voltage-level-dialog.js, src/components/dialogs/network-modifications/line-attach-to-voltage-level/line-attach-to-voltage-level-form.js, src/components/dialogs/network-modifications/line-split-with-voltage-level/line-split-with-voltage-level-dialog.js, src/components/dialogs/network-modifications/line-split-with-voltage-level/line-split-with-voltage-level-form.js
Format new voltage level in the form initialisation to avoid the isDirty at the beginning
=> Format new voltage level in the form initialisation

src/components/run-button-container.js
Reset state on computation launch which allows for further interrupts Applies to the following computations : all buses shortcircuit, voltage init and sensitivity analysis
=> Fix computation interrupt

src/services/study/dynamic-simulation.js
API has changed and now returns nothing => must use function backendFetch instead of backendFetchJson
=> [GridDyna] Exception when running dynamic simulation

src/components/dialogs/parameters/dynamicsimulation/curve/common/checkbox-select.js, src/components/dialogs/parameters/dynamicsimulation/curve/dialog/model-filter.js
=> Dynamic Simulation - Curve config - Disable uncheck if only one model present in 'Model association'

src/components/dialogs/parameters/dynamicsimulation/curve/dialog/model-filter.js
FIX for https://github.com/gridsuite/gridstudy-app/pull/1897
After fix
=> Dynamic Simulation - FIX variable vs variable set translation

src/components/app-wrapper.js, src/components/dialogs/dynamicsimulation/event/dynamic-simulation-event-dialog.tsx, src/components/graph/menus/dynamic-simulation/event-list-item.tsx, src/components/graph/menus/dynamic-simulation/event-modification-scenario-editor.tsx, src/translations/dynamic/events-locale-en.ts, src/translations/dynamic/events-locale-fr.ts, src/translations/dynamic/menu-locale-en.ts, src/translations/dynamic/menu-locale-fr.ts
Regression from : https://github.com/gridsuite/gridstudy-app/pull/1921/files#diff-e67939fd25c650222db710f18764d10ae69454b0e8ad680f5e10177c2db93ceaL332-L342
After corrected
=> Dynamic Simulation - Correct regression on event label

src/components/menus/operating-status-menu.js
Regression from : https://github.com/gridsuite/gridstudy-app/pull/1911/files#diff-3fd39f972d4c06b5251de35d3f305b54dcd0849e9b5a94aad91b126948f92407R254
after corrected
=> Dynamic Simulation - Correct regression on trip line and transformer

.github/workflows/build.yml, package-lock.json, vite.config.ts
Clean dirty package-lock
Remove useless emotion config
Reorder npm scripts for the GitHub pipeline
=> Clean after vite migration

src/components/dialogs/network-modifications/vsc/modification/vsc-modification-dialog.tsx
fix previous form value in vsc modification
=> fix previous value in vsc-modification

.browserslistrc, .eslintrc.json, package.json
Extract ESlint & BrowserList configs from `package.json`.  
Finish extraction of tools configurations from `package.json` initiated in #1919.
=> Finish extracting tools configs from `package.json`

src/components/custom-aggrid/custom-aggrid-header-utils.ts, src/components/custom-aggrid/custom-aggrid-header.jsx, src/components/custom-aggrid/custom-aggrid-header.type.ts, src/components/spreadsheet/enum-cell-renderer.tsx, src/components/spreadsheet/table-wrapper.jsx, src/components/spreadsheet/utils/config-tables.js, src/components/spreadsheet/utils/equipment-table-editors.jsx, src/components/utils/utils.js
Implement translation for enums in spreadsheet cell rendering, filtering and row edition.
=> Translate enums in spreadsheet

public/idpSettings.json, vite.config.ts
Dependents with gridsuite/deployment#401
=> Update server port to 3004

src/components/network/network-map-tab.jsx
This update resolves a critical issue where the network map was entering an infinite loop following updates from load flow results. We have refined the function responsible for reloading map equipment and separated it from the function that handles updates triggered by study impacts. This adjustment prevents recursive updating and enhances the stability of the network map.
=> Resolve Infinite Loop in Network Map Triggered by Load Flow Results

src/redux/store.js
Updated store.js to prevent state reset with HMR in development environment.
=> HMR support for redux store

src/components/utils/running-status.ts
Create a new status for failures of shortcircuit computation
=> add status FAILED for shortcircuit computation

src/components/dialogs/export-dialog.jsx
Since https://github.com/powsybl/powsybl-network-store-server/commit/257f14a07f02c59aabfc2323a7a7495a2594b223 was merged, we don't have performance issues anymore and we can enable CGMES export.
=> Enable cgmes export

src/components/graph/util/use-modification-label-computer.jsx
Following to previous PR: https://github.com/gridsuite/gridstudy-app/pull/2176
Before 
After
=> Change label for hvdc deletion in modification items

package-lock.json, package.json, src/components/diagrams/networkAreaDiagram/network-area-diagram-content.jsx
Adds non breaking change new parameters to the networkareadiagram constructor.
=> powsybl-diagram-viewer update to 0.5.5

src/services/study/network-modifications.js
A revert from previous PR: https://github.com/gridsuite/gridstudy-app/pull/2186
Tested => OK
=> Revert refactorisation url for change order

src/components/dialogs/network-modifications/voltage-level/creation/voltage-level-creation-dialog.jsx
FIX after merge : https://github.com/gridsuite/gridstudy-app/commit/3ea6d0195cbbbaeab1c730a10cbbf96a31806c1d#diff-013ec1e43e524aa7dba8888651fdc724212565624184af92028eaf93e8c3ba6fR1211
=> [FIX] Create Voltage Level

src/components/spreadsheet/table-wrapper.tsx, src/translations/spreadsheet-fr.ts
- Updated the translation of the tooltip for custom spreadsheets in `spreadsheet-fr.ts`.
- Aligned toolbar buttons in the UI for better visual consistency.
=> Spreadsheet minor changes : Update tooltip translation and aligned toolbar buttons

src/components/dialogs/network-modifications/common/properties/property-utils.ts, src/components/dialogs/network-modifications/hvdc-line/lcc/creation/filters-shunt-compensator-table.tsx, src/components/dialogs/network-modifications/hvdc-line/lcc/creation/lcc-converter-station.tsx, src/components/dialogs/network-modifications/hvdc-line/lcc/creation/lcc-creation-dialog-tabs.tsx, src/components/dialogs/network-modifications/hvdc-line/lcc/creation/lcc-creation-dialog.tsx, src/components/dialogs/network-modifications/hvdc-line/lcc/creation/lcc-creation.type.ts, src/components/utils/field-constants.ts
- Correct add/remove shunt compensators (conflict field id with useFieldArray)
- Correct missing Direction, Name and Position when reopen (bad typing with dto of creationInfos)
=> Create LLC (Thang Propose)

src/components/dialogs/parameters/network-visualizations/network-visualizations-parameters.tsx, src/components/parameters-tabs.tsx
Handle confirmation popup when changing the tabs with with changes in progress in the network visualizations tab.
=> Handle confirmation popup when changing the tabs

src/components/dialogs/network-modifications/tabular-modification/tabular-modification-utils.ts
To avoid changing actual behaviour
=> Ignore maxSusceptance and maxQAtNominalV conversion in tabular

src/components/dialogs/parameters/common/limitreductions/columns-definitions.ts
Reverts gridsuite/gridstudy-app#2481
=> Revert "disable developer mode for limit reductions"

src/components/results/securityanalysis/security-analysis-result-tab.tsx
fix(SecurityAnalysisResultTab): 
* Fix tab index management with enableDeveloperMode
* Fix pagination param states update and definition for fetching results
=> Fix missing SA results NMK when enableDeveloperMode is false

src/components/custom-aggrid/custom-aggrid-filters/custom-aggrid-autocomplete-filter.tsx, src/components/custom-aggrid/custom-aggrid-filters/custom-aggrid-boolean-filter.tsx, src/components/custom-aggrid/custom-aggrid-filters/custom-aggrid-comparator-filter.tsx, src/components/custom-aggrid/custom-aggrid-filters/custom-aggrid-duration-filter.tsx, src/components/custom-aggrid/custom-aggrid-filters/custom-aggrid-filter.tsx, src/components/custom-aggrid/custom-aggrid-filters/custom-aggrid-filter.type.ts, src/components/custom-aggrid/custom-aggrid-filters/custom-aggrid-text-filter.tsx, src/components/custom-aggrid/custom-aggrid-filters/hooks/use-custom-aggrid-comparator-filter.ts, src/components/custom-aggrid/custom-aggrid-filters/hooks/use-custom-aggrid-filter.ts, src/components/custom-aggrid/custom-aggrid-filters/utils/aggrid-filters-utils.ts, src/components/custom-aggrid/custom-aggrid-filters/utils/filter-tolerance-utils.ts, src/components/custom-aggrid/custom-aggrid-header-utils.ts, src/components/custom-aggrid/custom-aggrid-header.tsx, src/components/custom-aggrid/custom-aggrid-header.type.ts, src/components/report-viewer/log-table.tsx, src/components/results/dynamicsimulation/dynamic-simulation-result-timeline.tsx, src/components/results/loadflow/load-flow-result-tab.tsx, src/components/results/loadflow/load-flow-result-utils.ts, src/components/results/securityanalysis/security-analysis-result-utils.ts, src/components/results/securityanalysis/use-security-analysis-column-defs.tsx, src/components/results/shortcircuit/shortcircuit-analysis-result-table.tsx, src/components/results/shortcircuit/shortcircuit-analysis-result.tsx, src/components/spreadsheet/config/common-column-definitions.ts, src/components/spreadsheet/custom-columns/use-custom-column.ts, src/components/spreadsheet/table-wrapper.tsx
Solves :
- custom-aggrid-header.type.ts
11:1  error  Dependency cycle via ../spreadsheet/custom-columns/custom-columns-dialog:13  import/no-cycle
- custom-column-menu.tsx
13:1  error  Dependency cycle via components/custom-aggrid/custom-aggrid-header.type:53  import/no-cycle
- custom-columns-dialog.tsx
35:1  error  Dependency cycle via components/custom-aggrid/custom-aggrid-header.type:8=>./custom-column-menu:11  import/no-cycle
- custom-columns-form.tsx
8:1  error  Dependency cycle via ./custom-column-menu:11=>../spreadsheet/custom-columns/custom-columns-dialog:13  import/no-cycle
=> Fixes aggrid header dependency cycle

src/components/dialogs/parameters/dynamicsimulation/curve/common/checkbox-treeview.tsx, src/components/dialogs/parameters/dynamicsimulation/curve/dialog/curve-selector.tsx, src/components/dialogs/parameters/dynamicsimulation/curve/dialog/model-filter.tsx, src/components/dialogs/parameters/dynamicsimulation/dynamic-simulation-parameters.tsx, src/components/dialogs/parameters/dynamicsimulation/dynamic-simulation.type.ts, src/components/dialogs/parameters/dynamicsimulation/solver-parameters.tsx
Solves :
- checkbox-treeview.tsx
15:1  error  Dependency cycle detected  import/no-cycle
- model-filter.tsx
12:1  error  Dependency cycle detected  import/no-cycle
- dynamic-simulation-parameters.tsx
14:1  error  Dependency cycle detected  import/no-cycle
- solver-parameters.tsx
15:1  error  Dependency cycle detected  import/no-cycle
=> Fixes dynamic simulation parameters deps cycles

src/components/dialogs/parameters/non-evacuated-energy/non-evacuated-energy-parameters.tsx, src/components/dialogs/parameters/non-evacuated-energy/utils.ts
Solves :
- non-evacuated-energy-parameters.tsx
50:1  error  Dependency cycle detected  import/no-cycle
- non-evacuated-energy/utils.ts
38:1  error  Dependency cycle detected  import/no-cycle
=> Fixes non evacuated energy parameters deps cycles

src/components/dialogs/parameters/sensi/sensitivity-analysis-parameters.tsx, src/components/dialogs/parameters/sensi/utils.ts
Solves :
- sensitivity-analysis-parameters.tsx
59:1  error  Dependency cycle detected  import/no-cycle
- sensi/utils.ts
32:1  error  Dependency cycle detected  import/no-cycle
=> Fixes sensi parameters deps cycles

src/components/dialogs/parameters/voltageinit/voltage-init-parameters-form.tsx, src/components/dialogs/parameters/voltageinit/voltage-init-utils.ts, src/components/dialogs/parameters/voltageinit/voltage-init.type.ts
Solves : 
- voltage-init-parameters-form.tsx
28:1  error  Dependency cycle detected  import/no-cycle
- voltage-init-utils.ts
29:1  error  Dependency cycle detected  import/no-cycle
=> Fixes voltage init parameters deps cycles

src/components/app-top-bar.jsx, src/components/diagrams/diagram-common.ts, src/components/diagrams/diagram-pane.tsx, src/components/diagrams/diagram-utils.ts, src/components/diagrams/diagram.tsx, src/components/diagrams/diagram.type.ts, src/components/diagrams/networkAreaDiagram/network-area-diagram-content.tsx, src/components/diagrams/singleLineDiagram/position-diagram-pane.tsx, src/components/diagrams/singleLineDiagram/single-line-diagram-content.tsx, src/components/diagrams/use-diagram.ts, src/components/dialogs/parameters/network-visualizations/network-visualizations-utils.ts, src/components/map-viewer.jsx, src/components/study-pane.jsx, src/components/top-bar-equipment-seach-dialog/custom-suffix-renderer.tsx, src/redux/actions.ts, src/redux/reducer.test.ts, src/redux/reducer.ts
Solves :
- store.ts
9:1  error  Dependency cycle via ../components/diagrams/diagram-common:228  import/no-cycle
- gs-map-equipments.ts
11:1  error  Dependency cycle detected                                                                                  import/no-cycle
13:1  error  Dependency cycle via ./index:11=>components/diagrams/diagram-common:20=>../../redux/store:15=>./reducer:9  import/no-cycle  
- diagram-common.ts
10:1  error  Dependency cycle detected         import/no-cycle
15:1  error  Dependency cycle via ./reducer:9  import/no-cycle   
- network.ts
11:1  error  Dependency cycle via components/diagrams/diagram-common:20=>../../redux/actions:10=>components/network/gs-map-equipments:51  import/no-cycle  
- filter.ts
10:1  error  Dependency cycle via …
=> Fixes diagram deps cycle

.eslintrc.json, package-lock.json, package.json, src/components/diagrams/diagram-common.ts, src/components/dialogs/parameters/use-parameters-state.ts, src/components/graph/network-modification-tree-model.ts, src/components/graph/util/model-functions.ts, src/components/results/common/results-global-filter.tsx, src/components/results/securityanalysis/security-analysis-result-utils.ts, src/redux/actions.ts, src/redux/reducer.ts, src/redux/utils.ts, src/services/study/index.ts
Adds no-cycle and no-self-import eslint rules and also solves : 
- model-functions.ts
9:1  error  Dependency cycle detected  import/no-cycle
10:1  error  Dependency cycle detected  import/no-cycle
- network-modification-tree-model.ts
8:1  error  Dependency cycle detected  import/no-cycle
12:1  error  Dependency cycle detected  import/no-cycle
- reducer.ts
31:1  error  Dependency cycle via ../components/graph/network-modification-tree-model:20  import/no-cycle
228:1  error  Dependency cycle via ../../redux/store:15                                    import/no-cycle
229:1  error  Dependency cycle detected                                                    import/no-cycle
270:1  error  Dependency cycle detected  
- use-parameters-state.ts
13:1  error  Dependency cycle via …
=> Fixes all remaining deps cycle

src/components/diagrams/diagram-pane.tsx, src/services/study/geo-data.ts, src/services/study/index.ts
Change get mappings for NAD and geo-data lines and substations fetching to post mapping with ids in the request body (it avoids oversized headers).
=> Change mapping to post and pass ids (substations/voltage levels) in request body

src/components/spreadsheet/constants.ts, src/components/spreadsheet/custom-spreadsheet/custom-spreadsheet-config.tsx, src/components/spreadsheet/custom-spreadsheet/dialogs/spreadsheets-from-collection-dialog.tsx, src/components/spreadsheet/equipment-tabs.tsx
Fix tab selection bug after importing a new collection or deleting a tab
=> Fix spreadsheets dnd

src/components/map-viewer.jsx, src/components/network-modification-tree-pane.jsx, src/components/network/network-map-tab.tsx, src/redux/actions.ts, src/redux/reducer.ts
fix(): use mapDataLoading, setting its value accordingly in the process
=> refactor(): remove mapMissingDataLoading usage

package-lock.json, package.json, src/components/spreadsheet/custom-spreadsheet/dialogs/spreadsheet-from-model-dialog.tsx, src/components/spreadsheet/custom-spreadsheet/dialogs/spreadsheets-from-collection-dialog.tsx
requires a new release of commons-ui, cf https://github.com/gridsuite/commons-ui/pull/767
=> Browse a single element when we import a spreadsheet model or collection

src/components/dialogs/network-modifications/voltage-level-topology-modification/connection-cell-render.tsx, src/components/dialogs/network-modifications/voltage-level-topology-modification/voltage-level-topology-modification-dialog.tsx, src/components/dialogs/network-modifications/voltage-level-topology-modification/voltage-level-topology-modification-form.tsx, src/components/dialogs/network-modifications/voltage-level-topology-modification/voltage-level-topology.type.ts
Following to PR: https://github.com/gridsuite/gridstudy-app/pull/2814
=> Fix Open vs Close in modifying voltage level topology

src/components/graph/menus/network-modifications/network-modification-node-editor.tsx
Refresh excluded modifications when notifications are received.
=> Fix root network chip : update on notification reception

src/translations/fr.json
Signed-off-by: Etienne LESOT <etienne.lesot@rte-france.com>
=> fix label in modification menu

src/components/results/sensitivity-analysis/sensitivity-analysis-result-utils.ts
Same as other computation types
=> Remove "all" from page options in sensitivity analysis result
